swagger: '2.0'
info:
  title: Inntinn
  version: '1.1'
  license:
    name: Apache 2.0
    url: 'https://github.com/BlackburnHax/inntinn/blob/main/LICENSE'
  description: ''
  summary: Meta risk analysis and scoring system based on open-source fully automated intelligence gathering
  contact:
    name: Brandon Blackburn
    url: 'https://bhax.net'
  termsOfService: 'https://github.com/BlackburnHax/inntinn/blob/main/LICENSE'
servers:
  - url: 'http://localhost:443'
paths:
  /cik:
    post:
      summary: Lookup company CIK
      tags: []
      responses:
        '200':
          description: OK
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                '63330': MAUI LAND & PINEAPPLE CO INC
                '320193': Apple Inc.
                '1144326': APPLETON PAPERS INC/WI
                '1277151': APPLE REIT SIX INC
                '1329011': 'APPLE REIT SEVEN, INC.'
                '1387361': 'APPLE REIT EIGHT, INC.'
                '1418121': 'APPLE HOSPITALITY REIT, INC.'
                '1498864': 'APPLE REIT TEN, INC.'
                '1510976': 'APPLE GREEN HOLDING, INC.'
                '1654672': 'PINEAPPLE, INC.'
            properties:
              CIK:
                type: string
          examples:
            Example Response to "apple":
              '63330': MAUI LAND & PINEAPPLE CO INC
              '320193': Apple Inc.
              '1144326': APPLETON PAPERS INC/WI
              '1277151': APPLE REIT SIX INC
              '1329011': 'APPLE REIT SEVEN, INC.'
              '1387361': 'APPLE REIT EIGHT, INC.'
              '1418121': 'APPLE HOSPITALITY REIT, INC.'
              '1498864': 'APPLE REIT TEN, INC.'
              '1510976': 'APPLE GREEN HOLDING, INC.'
              '1654672': 'PINEAPPLE, INC.'
      operationId: post-cik
      description: Looks up all matching companies given the supplied company name
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                lookup:
                  type: string
                  minLength: 1
              required:
                - lookup
              x-examples:
                example-1:
                  lookup: apple
            examples:
              example-1:
                value:
                  lookup: string
      parameters:
        - in: body
          name: body
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                key: change_me
            properties:
              key:
                type: string
                minLength: 1
            required:
              - key
  /cve:
    post:
      summary: Lookup CVE
      tags: []
      responses:
        '200':
          description: OK
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                _id: CVE-2019-0708
                description: A remote code execution.
                obtainAllPrivilege: false
                obtainOtherPrivilege: false
                obtainUserPrivilege: false
                references:
                  - 'http://packetstormsecurity.com/files/155389/Microsoft-Windows-7-x86-BlueKeep-RDP-Use-After-Free.html'
                userInteractionRequired: false
                v2_score: 10
                v3_score: 9.8
            properties:
              _id:
                type: string
                minLength: 1
              description:
                type: string
                minLength: 1
              obtainAllPrivilege:
                type: boolean
              obtainOtherPrivilege:
                type: boolean
              obtainUserPrivilege:
                type: boolean
              references:
                type: array
                items:
                  type: string
              userInteractionRequired:
                type: boolean
              v2_score:
                type: number
              v3_score:
                type: number
            required:
              - _id
              - description
              - obtainAllPrivilege
              - obtainOtherPrivilege
              - obtainUserPrivilege
              - references
              - userInteractionRequired
              - v2_score
              - v3_score
      operationId: post-cve
      description: Retrieve available information on a given NVD CVE ID
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                lookup:
                  type: string
                  minLength: 1
              required:
                - lookup
              x-examples:
                example-1:
                  lookup: CVE-2019-0708
      parameters:
        - in: body
          name: body
          schema:
            description: ''
            type: object
            properties:
              lookup:
                type: string
                minLength: 1
            required:
              - lookup
            x-examples:
              example-1:
                lookup: CVE-2019-0708
  /score:
    post:
      summary: Compute Inntinn Score
      tags: []
      responses:
        '200':
          description: OK
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                score: 48
                confidence: 54
            properties:
              score:
                type: number
              confidence:
                type: number
                description: How confident (1-100) that the score is accurate based on Fuzzy matching. Only present in NON-CIK searches.
            required:
              - score
          examples:
            Fuzzy Search Result:
              score: 48
              confidence: 54
            Exact Search by CIK:
              score: 78
      operationId: post-score
      description: Calculate a final score for a given device which is vulnerable to the list of CVEs and is found in the company identified by CIK or partial name match
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  cves:
                    - CVE-2019-0708
                    - CVE-1999-0019
                    - CVE-2018-0880
                    - CVE-2021-22721
                  company: apple
              properties:
                cves:
                  type: array
                  items:
                    type: string
                company:
                  type:
                    - string
                    - integer
                  minLength: 1
              required:
                - cves
                - company
            examples:
              Fuzzy Matching:
                value:
                  cves:
                    - CVE-2019-0708
                    - CVE-1999-0019
                    - CVE-2018-0880
                    - CVE-2021-22721
                  company: apple
              Precise Matching on CIK:
                value:
                  cves:
                    - CVE-2019-0708
                    - CVE-1999-0019
                    - CVE-2018-0880
                    - CVE-2021-22721
                  company: 320193
      parameters:
        - in: body
          name: body
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                cves:
                  - CVE-2019-0708
                  - CVE-1999-0019
                  - CVE-2018-0880
                  - CVE-2021-22721
                company: apple
            properties:
              cves:
                type: array
                items:
                  type: string
              company:
                type: string
                minLength: 1
            required:
              - cves
              - company
          x-examples:
            Fuzzy Search:
              cves:
                - CVE-2019-0708
                - CVE-1999-0019
                - CVE-2018-0880
                - CVE-2021-22721
              company: apple
            Exact CIK search:
              cves:
                - CVE-2019-0708
                - CVE-1999-0019
                - CVE-2018-0880
                - CVE-2021-22721
              company: 320193
  /score/org:
    post:
      summary: Compute Org Score
      tags: []
      responses:
        '200':
          description: OK
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                org_score: 141
            properties:
              org_score:
                type: integer
            required:
              - org_score
          examples:
            Standard Usage:
              org_score: 141
      operationId: post-score-org
      description: 'Creates a single company-wide score that can measure overall risk in relation to other companies, or over time..'
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  scores:
                    - 22
                    - 15
                    - 99
                    - 5
              properties:
                scores:
                  type: array
                  items:
                    type: integer
              required:
                - scores
            examples:
              Basic Usage:
                value:
                  scores:
                    - 22
                    - 15
                    - 99
                    - 5
      parameters:
        - in: body
          name: body
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                scores:
                  - 22
                  - 15
                  - 99
                  - 5
            properties:
              scores:
                type: array
                items:
                  type: integer
            required:
              - scores
          x-examples:
            Standard usage:
              scores:
                - 22
                - 15
                - 99
                - 5
  /server:
    post:
      summary: Server Admin
      operationId: post-server
      responses:
        '200':
          description: OK
      description: Updates all internal databases using freshly downloaded data
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                key:
                  type: string
                  minLength: 1
              required:
                - key
              x-examples:
                example-1:
                  key: change_me
            examples:
              Basic Usage:
                value:
                  key: change_me
        description: ''
components:
  schemas: {}
